name: SetupBranch

on:
  workflow_dispatch:
    inputs:
      target_branch:
        type: string
        required: true
        description: "Temporary branch to create (NewUpdate will commit to that branch)."
      sirius_version:
        description: "Optional: specify SIRIUS version to use (e.g. 6.3.3)"
        required: false
        type: string

jobs:
  CreateTempBranch:
    runs-on: ubuntu-latest
    outputs:
      target_branch: ${{ steps.output.outputs.target_branch }}
    steps:
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ inputs.target_branch }}
      - name: Set output
        id: output
        run: |
          echo "target_branch=${{ inputs.target_branch }}" >> $GITHUB_OUTPUT

  UpdateOnNewBranch:
    needs: CreateTempBranch
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Call NewUpdate
        run: |
          if [ -n "${{ inputs.sirius_version }}" ]; then
            gh workflow run NewUpdate.yml --ref ${{ inputs.target_branch }} -f target_branch=${GITHUB_REF##*/} -f sirius_version=${{ inputs.sirius_version }}
          else
            gh workflow run NewUpdate.yml --ref ${{ inputs.target_branch }} -f target_branch=${GITHUB_REF##*/}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}