name: SetupBranch

on:
  workflow_dispatch:
    inputs:
      target_branch:
        type: string
        required: true
      sirius_version:
        description: "Optional: specify SIRIUS version to use (e.g. 6.3.3)"
        required: false
        type: string

jobs:
  CreateTempBranch:
    runs-on: ubuntu-latest
    steps:
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ inputs.target_branch }}

  UpdateOnNewBranch:
    needs: CreateTempBranch
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Call NewUpdate
        run: |
          version_input=""
          if [ -n "${{ inputs.sirius_version }}" ]; then
            version_input="-f sirius_version=${{ inputs.sirius_version }}"
          fi
          gh workflow run NewUpdate.yml --ref ${{ inputs.target_branch }} -f target_branch=${GITHUB_REF##*/} $version_input
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
